kind: pipeline
name: <pipeline>

trigger:
  branch:
    - stage
  event:
    - push

volumes:
  - name: docker_daemon
    host:
      path: /var/run/docker.sock
  - name: docker_cache
    host:
      path: /mnt/drone-docker

steps:
  - name: build web
    image: docker:dind
    environment:
      REGISTRY_USER:
        from_secret: docker_username
      REGISTRY_PASS:
        from_secret: docker_password
    volumes:
      - name: docker_cache
        path: /var/lib/docker
      - name: docker_daemon
        path: /var/run/docker.sock
    commands:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.vivifyideas.com
      - docker build -f Dockerfile -t registry.vivifyideas.com/<namespace>/web:${DRONE_BRANCH} --build-arg REQUIREMENTS_FILE=prod.txt --pull=true .
      - docker push registry.vivifyideas.com/<namespace>/web:${DRONE_BRANCH}
      - docker build -f Dockerfile-static -t registry.vivifyideas.com/<namespace>/static:${DRONE_BRANCH} --pull=true .
      - docker push registry.vivifyideas.com/<namespace>/static:${DRONE_BRANCH}
      - docker image prune -f

  - name: deploy
    image: alpine
    environment:
      BRANCH: ${DRONE_BRANCH}
    commands:
      - apk add --no-cache curl
      - sh deploy.sh

  - name: slack
    image: plugins/slack
    when:
      status: [ success, failure ]
    settings:
      webhook:
        from_secret: slack_webhook
      channel: <channel>

