# Generated by Django 2.1.9 on 2019-09-09 14:24

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190905_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
