# Generated by Django 3.2.12 on 2024-02-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_subscribe_analysts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='user',
            new_name='analyst_user_id',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='analyst_id',
            new_name='id',
        ),
    ]
