# Generated by Django 3.2.12 on 2024-02-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240227_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='analyst_user_id',
            new_name='analyst_user',
        ),
    ]
