# Generated by Django 3.2.12 on 2024-02-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_id_analysis_analysis_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='analysis_id',
            new_name='id',
        ),
    ]
